### ISSUE TITLE
Generalization of CoKL for more than two incomplete data sets

### ISSUE THREAD

**Issue by amirms** [software-shao/Collective-Kernel-Learning#1]
The CoKL algorithm as implemented here is restricted to two incomplete views. I would like to generalize the implementation for more than two views. The paper suggests as to how this should be done. Would you describe how the current implementation can be extended to generalize this?

**Comment by software-shao** [comment]
Hi amirms,

One way to extend this to multiple views is to apply this method pairwise or in a loop fashion. For example, if we have view 1,2,3,...,k. We can apply this method to view 1,2, then view 2,3, then view 3,4. ... then view k-1, k. until it converges.

However, this paper is my very early attempt for multi-view clustering problem. You can also read/use the code from my more recent papers [1] and [2].
[1] https://github.com/software-shao/Multi-Incomplete-view-Clustering
Shao, W., He, L. and Philip, S.Y., 2015, September. Multiple Incomplete Views Clustering via Weighted Nonnegative Matrix Factorization with L_ {2, 1} Regularization. In Joint European Conference on Machine Learning and Knowledge Discovery in Databases (pp. 318-334). Springer International Publishing.
[2] https://github.com/software-shao/online-multiview-clustering-with-incomplete-view
Shao, W., He, L., Lu, C.T. and Philip, S.Y., 2016, December. Online multi-view clustering with incomplete views. In Big Data (Big Data), 2016 IEEE International Conference on (pp. 1012-1017). IEEE.
